### ISSUE TITLE
accessing the filtered table

### ISSUE THREAD

**Issue by Rizver** [Dynamitable/Dynamitable#2]
Hello,

Thanks for this good plugin! Can you please give an example as to how one can access the filtered table (tbody)

Thanks in advance!

**Comment by ronfroy** [comment]
Dynamitable hides columns with jQuery . You can use some thing like this:

$('.js-dynamitable tbody tr:visible');

https://api.jquery.com/visible-selector/

**Comment by Rizver** [comment]
thanks alot !!! I appreciate the so quick response :))
